services:
  # خدمة الداتابيز
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=${AP_POSTGRES_DATABASE:-yflow}'
      - 'POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD:-password}'
      - 'POSTGRES_USER=${AP_POSTGRES_USERNAME:-postgres}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yflow_net

  # خدمة الـ Redis
  redis:
    image: 'redis:7.0.7'
    container_name: redis
    restart: unless-stopped
    volumes:
      - 'redis_data:/data'
    networks:
      - yflow_net

  # خدمة التطبيق (تم تصحيح الحروف الكبيرة هنا)
  yflow_app:
    image: ghcr.io/yflow/yflow:0.73.0
    container_name: yflow_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file: .env
    volumes:
      - ./cache:/usr/src/app/cache
    networks:
      - yflow_net

volumes:
  postgres_data:
  redis_data:

networks:
  yflow_net:
