encryptionsalt: v1:icXg2cmIvSc=:v1:y8+4YhdMCPPDY26J:5cNYmimH353n8sjUDDc6srvcPgb+8Q==
config:
  Yflow:environment: "prod"
  Yflow:apEncryptionKey:
  Yflow:apJwtSecret:
  Yflow:deployLocalBuild: "true"
  Yflow:repoName: "Yflow-prod-repo"
  Yflow:containerCpu: "512"
  Yflow:containerMemory: "1024"
  Yflow:containerInstances: "1"
  Yflow:usePostgres: "true"
  Yflow:dbInstanceClass: "db.t3.small"
  Yflow:dbIsPublic: "false"
  Yflow:dbPassword:
    secure: v1:MXNSOcqZCp10X2PX:mU2iTrcETjdisk8FkD5yHLJYUxRei/9l
  Yflow:dbUsername: "postgres"
  Yflow:useRedis: "true"
  Yflow:redisNodeType: "cache.t3.small"
  aws:region: "us-east-1"
